import './globals.css'
import NextHead from 'next/head'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <NextHead>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet" />
      </NextHead>
      <html lang="en">
        <body>{children}</body>
      </html>
    </>
    
  )
}
