"use client"

import './globals.css'
import { Montserrat } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import { ReactNode } from 'react'
import { useSession } from 'next-auth/react'

interface IProps {
  children: ReactNode
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const montserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
})

export default function RootLayout({ children }: IProps) {

  return (
    <html lang="en">
      <body className={`${montserrat}`}>
        {children}
      </body>
    </html>
  )
}
